apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: elasticsearchclusters.elasticsearch.k8s.elastic.co
spec:
  group: elasticsearch.k8s.elastic.co
  names:
    categories:
    - elastic
    kind: ElasticsearchCluster
    plural: elasticsearchclusters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            expose:
              enum:
              - ClusterIP
              - LoadBalancer
              - NodePort
              type: string
            featureFlags:
              type: object
            image:
              type: string
            setVmMaxMapCount:
              type: boolean
            snapshotRepository:
              properties:
                settings:
                  properties:
                    bucketName:
                      type: string
                    credentials:
                      type: object
                  type: object
                type:
                  enum:
                  - gcs
                  type: string
              required:
              - type
              - settings
              type: object
            topologies:
              items:
                properties:
                  nodeCount:
                    format: int32
                    type: integer
                  nodeTypes:
                    properties:
                      data:
                        type: boolean
                      ingest:
                        type: boolean
                      master:
                        type: boolean
                      ml:
                        type: boolean
                    type: object
                  resources:
                    properties:
                      limits:
                        type: object
                    type: object
                  template:
                    properties:
                      metadata:
                        type: object
                      spec:
                        properties:
                          affinity:
                            type: object
                        type: object
                    type: object
                  volumeClaimTemplates:
                    items:
                      type: object
                    type: array
                type: object
              type: array
            updateStrategy:
              properties:
                groups:
                  items:
                    properties:
                      selector:
                        type: object
                    type: object
                  type: array
                strategy:
                  properties:
                    maxSurge:
                      format: int64
                      type: integer
                    maxUnavailable:
                      format: int64
                      type: integer
                  type: object
              type: object
            version:
              type: string
          type: object
        status:
          properties:
            clusterUUID:
              type: string
            health:
              type: string
            masterNode:
              type: string
            phase:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
