apiVersion: deployments.k8s.elastic.co/v1alpha1
kind: Stack
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: stack-sample
spec:
  # Add fields here
  version: "6.4.2"
  featureFlags:
    nodeCertificates:
      enabled: true
  elasticsearch:
    setVmMaxMapCount: true
    topologies:
    - nodeTypes:
        master: true
        data: true
        ingest: true
      resources:
        limits:
          mem: 1Gi
          storage: 1GB
          cpu: 800m
      nodeCount: 3
      ## this shows how to add a custom label to all pods created for this topology element
      #template:
      #  metadata:
      #    labels:
      #      foo: bar
      ## this shows how to request 2Gi of persistent data storage for pods in this topology element
      #volumeClaimTemplates:
      #- metadata:
      #    name: data
      #  spec:
      #    accessModes:
      #    - ReadWriteOnce
      #    resources:
      #      requests:
      #        storage: 2Gi
  kibana:
    nodeCount: 1
    expose: LoadBalancer
