apiVersion: deployments.k8s.elastic.co/v1alpha1
kind: Stack
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: stack-sample
spec:
  version: "6.4.2"
  elasticsearch:
    setVmMaxMapCount: true
    updateStrategy:
      groups:
      # update master nodes first:
      - selector:
          matchLabels:
            elasticsearch.k8s.elastic.co/node-master: "true"
        strategy:
          maxSurge: 1
    topologies:
    - nodeTypes:
        master: true
        data: true
        ingest: true
      resources:
        limits:
          memory: 1Gi
          cpu: 800m
      nodeCount: 3
      ## this shows how to add a custom label to all pods created for this topology element
      #template:
      #  metadata:
      #    labels:
      #      foo: bar
      ## this shows how to request 2Gi of persistent data storage for pods in this topology element
      #volumeClaimTemplates:
      #- metadata:
      #    name: data
      #  spec:
      #    accessModes:
      #    - ReadWriteOnce
      #    resources:
      #      requests:
      #        storage: 2Gi
    # dedicated masters:
    - nodeTypes:
        master: true
        data: false
        ingest: false
      resources:
        limits:
          memory: 1Gi
          cpu: 800m
      nodeCount: 0
    # dedicated data nodes
    - nodeTypes:
        master: false
        data: true
        ingest: false
      resources:
        limits:
          memory: 1Gi
          cpu: 800m
      nodeCount: 0
    ## See the following as an example of how to configure a snapshot repository
    #snapshotRepository:
    #  type: "gcs"
    #  settings:
    #    bucketName: "stack-sample-snapshot-repo"
    #    credentials:
    #      namespace: "default"
    #      name: "gcs-repo-account"
    expose: LoadBalancer
  kibana:
    nodeCount: 1
    expose: LoadBalancer
